site:
  title: TW-PINT
  start_page: tw-pint::index.adoc

content:
  sources:
    - url: .
      branches: HEAD
      start_path: docs

ui:
  bundle:
    url: ./ui-bundle.zip
    snapshot: true

output:
  dir: ./build/site